### ISSUE TITLE
Define `shivablue` color 

### ISSUE THREAD

**Issue by wdconinc** [paulgessinger/mtng#1]
The created slides require the color `shivablue` to be defined. This is not available by default in at least my installation of texlive :-) I wonder if it would be possible to include the definition (or use something like `\providecolor{merged_pr_color}{rgb}{0.6,0.86,0.99}`, which will simply use `merged_pr_color` if it exists and use the [Shiva blue](https://icolorpalette.com/color/shiva-blue) if not).

**Comment by paulgessinger** [comment]
Oh, right. I actually just named the CERN blue "shiva blue" to be funny. I didn't think it would be required, sorry!
