### ISSUE TITLE
Gracefully deal with $ in issue titles...

### ISSUE THREAD

**Issue by wdconinc** [paulgessinger/mtng#5]
I guess the Acts developers have been more restrained in their use of special characters in issue and PR titles... It does not seem that just using `\verb` is sufficient here, since that doesn't work inside titles. It would probably require `cprotect` or so. Or changing the titles whenever they have something really egregious.

**Comment by wdconinc** [comment]
Maybe the `markdown` package.

**Comment by paulgessinger** [comment]
#13 adds an updated list of symbols that are cleaned. I guess `cprotect` could solve this for all cases, but I'm not quite sure how to fit that in here.

**Comment by wdconinc** [comment]
Thanks! FYI, we're using this in https://github.com/eic/generate-meeting-slides, and e.g. https://github.com/eic/epic/blob/main/.github/workflows/generate-weekly-meeting-slides.yml to structure our meetings.
